### ISSUE TITLE
one-third using a margin that messes it up?

### ISSUE THREAD

**Issue by dcolumbus** [cobyism/gridism#36]
I'm trying to use the "one-third" class, but there seems to be a margin-left rule that messes it up. When I turn off the rule, the grid responds the way it should:

```
media="all"
.five-sixths, .four-sixths, .one-fourth, .one-half, .one-sixth, .one-third, .three-fourths, .three-sixths, .two-fourths, .two-sixths, .two-thirds {
    float: left;
    margin-left: 2.564102564102564%;
}
```

With "margin-left" left in tact:

![screen shot 2015-07-27 at 10 32 40 am](https://cloud.githubusercontent.com/assets/895222/8912964/e1333dde-344a-11e5-895d-2cef2c69bd53.png)

When the "margin-left" is turned off:

![screen shot 2015-07-27 at 10 32 57 am](https://cloud.githubusercontent.com/assets/895222/8912972/e653397c-344a-11e5-8e45-b2e90195e941.png)

**Comment by cobyism** [comment]
That margin shouldn’t be there if the `.unit` is the first child of your `.grid` row, so my first instinct would be to check that you’re using separate `.grid`s for each horizontal row (i.e. instead of having *all* of the fields in your screenshot within a single `.grid`). Can you share what the markup is you’re using to implement your screenshot, perhaps in a [gist](https://gist.github.com/)?

**Comment by dcolumbus** [comment]
I'm using one grid DIV to house the three one-third units: https://gist.github.com/dcolumbus/d022f31f8b8e28c83b9f#file-gistfile1-txt

**Comment by cobyism** [comment]
Thanks for the Gist. I’ve had a bit of a play, and I can’t seem to replicate the issue from your screenshot. Here’s a link to a demo on CodePen with `gridism.css` included in the `<head>`, and markup as you describe: http://codepen.io/cobyism/pen/eNxMoQ?editors=110

[![2015-08-06 at 8 48 am](https://cloud.githubusercontent.com/assets/296432/9106482/7d42614e-3c18-11e5-988d-40e8e8085cc9.png)](http://codepen.io/cobyism/pen/eNxMoQ?editors=110)

I also note that at the top of your issue description, you pasted some CSS containing:

```
margin-left: 2.564102564102564%;
```

… which seems odd to me because if you search through the [current `gridism.css` file](https://github.com/cobyism/gridism/blob/0456b81f158a14c7a37f68361f1c72be4e452356/gridism.css), the only values ever specified for `margin` are `margin: 0 auto;`. All other spacing is done using `padding` attributes.

Are you *sure* there’s nothing else in your site’s CSS providing that extra `margin`?
