### ISSUE TITLE
How about this? 

### ISSUE THREAD

**Issue by mpa3b** [cobyism/gridism#37]
If I use your grid unit'd content's widths aren't equal.
I use this code to fix it:

`.grid {
    margin: 0 -10px;
}

.unit:first-of-type {
    padding-left: 10px;
}

.unit:last-of-type {
    padding-right: 10px;
}

**Comment by cobyism** [comment]
Thanks for opening an issue. To make sure I understand the issue, are you able to link to a [minimal example](http://stackoverflow.com/help/mcve) showing the problem? perhaps using a tool like [JSFiddle](https://jsfiddle.net/) or [CodePen](http://codepen.io/pen/)?

**Comment by mpa3b** [comment]
http://codepen.io/anon/pen/BjMNmq

**Comment by cobyism** [comment]
Thanks for creating that example. Yeah, the way this is designed is to ensure that the whitespace created by the gutters are equal on the outside and the inside:

<img width="1006" alt="2016-02-12 at 9 11 pm" src="https://cloud.githubusercontent.com/assets/296432/13020475/84ec5102-d1cd-11e5-8389-e6382432933a.png">

Unfortunately, this does mean that the *inside space* of each `.unit` isn’t equal. If you want to ensure you have equal width units, it’s probably easier to just override like you have above, or create a dedicated component (perhaps using [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), since that now has fairly wide browser support, and gives you more control than frameworks like this that rely on floats etc.)

**Comment by mpa3b** [comment]
It's not aout the gutters, these are fine, but the images.
The sample images are equal, same dimensions of 400px.
But the display shows difference between them^ 295, 305, 295
